"""add user profile fields, movie financial fields, reviews table and watchlist indexes

Revision ID: 7c21e5e0ba5e
Revises: 0cc63cff7d09
Create Date: 2026-05-20 18:48:08.128296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c21e5e0ba5e'
down_revision: Union[str, Sequence[str], None] = '0cc63cff7d09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_public', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('rating >= 0 AND rating <= 10', name='review_rating_range'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'movie_id', name='uq_review_user_movie')
    )
    op.create_index('ix_reviews_movie', 'reviews', ['movie_id'], unique=False)
    op.create_index('ix_reviews_user', 'reviews', ['user_id'], unique=False)
    op.drop_constraint(op.f('movie_genres_genre_id_fkey'), 'movie_genres', type_='foreignkey')
    op.drop_constraint(op.f('movie_genres_movie_id_fkey'), 'movie_genres', type_='foreignkey')
    op.create_foreign_key(None, 'movie_genres', 'movies', ['movie_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'movie_genres', 'genres', ['genre_id'], ['id'], ondelete='CASCADE')
    op.add_column('movies', sa.Column('revenue', sa.BigInteger(), nullable=True))
    op.add_column('movies', sa.Column('budget', sa.BigInteger(), nullable=True))
    op.add_column('movies', sa.Column('runtime', sa.Integer(), nullable=True))
    op.add_column('movies', sa.Column('tagline', sa.String(length=500), nullable=True))
    op.add_column('movies', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('movies', sa.Column('original_language', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index('ix_watchlist_user_status', 'watchlist_entries', ['user_id', 'status'], unique=False)
    op.create_unique_constraint('uq_watchlist_user_movie', 'watchlist_entries', ['user_id', 'movie_id'])
    op.drop_constraint(op.f('watchlist_entries_user_id_fkey'), 'watchlist_entries', type_='foreignkey')
    op.drop_constraint(op.f('watchlist_entries_movie_id_fkey'), 'watchlist_entries', type_='foreignkey')
    op.create_foreign_key(None, 'watchlist_entries', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'watchlist_entries', 'movies', ['movie_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'watchlist_entries', type_='foreignkey')
    op.drop_constraint(None, 'watchlist_entries', type_='foreignkey')
    op.create_foreign_key(op.f('watchlist_entries_movie_id_fkey'), 'watchlist_entries', 'movies', ['movie_id'], ['id'])
    op.create_foreign_key(op.f('watchlist_entries_user_id_fkey'), 'watchlist_entries', 'users', ['user_id'], ['id'])
    op.drop_constraint('uq_watchlist_user_movie', 'watchlist_entries', type_='unique')
    op.drop_index('ix_watchlist_user_status', table_name='watchlist_entries')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'avatar_url')
    op.drop_column('movies', 'original_language')
    op.drop_column('movies', 'status')
    op.drop_column('movies', 'tagline')
    op.drop_column('movies', 'runtime')
    op.drop_column('movies', 'budget')
    op.drop_column('movies', 'revenue')
    op.drop_constraint(None, 'movie_genres', type_='foreignkey')
    op.drop_constraint(None, 'movie_genres', type_='foreignkey')
    op.create_foreign_key(op.f('movie_genres_movie_id_fkey'), 'movie_genres', 'movies', ['movie_id'], ['id'])
    op.create_foreign_key(op.f('movie_genres_genre_id_fkey'), 'movie_genres', 'genres', ['genre_id'], ['id'])
    op.drop_index('ix_reviews_user', table_name='reviews')
    op.drop_index('ix_reviews_movie', table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
